name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:

  chaincode_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/hyperledgendary/conga-nft-contract:${GITHUB_SHA}
    - name: Publish Docker image
      if: github.event_name != 'pull_request'
      run: |
        echo ${DOCKER_PW} | docker login ghcr.io -u ${DOCKER_USER} --password-stdin
        docker push ghcr.io/hyperledgendary/conga-nft-contract:${GITHUB_SHA}
      env:
        DOCKER_USER: ${{ github.actor }}
        DOCKER_PW: ${{ secrets.GITHUB_TOKEN }}

  chaincode_package:
    needs: chaincode_image
    runs-on: ubuntu-latest

    steps:
    - name: Create package
      uses: hyperledgendary/package-k8s-chaincode-action@c17c59bc25075080c9167cb26a0008c9ff925494
      with:
        chaincode-label: conga-nft-contract
        chaincode-image: ghcr.io/hyperledgendary/conga-nft-contract
        chaincode-tag: $GITHUB_SHA
    - name: Rename package
      run: mv conga-nft-contract.tgz conga-nft-contract-${GITHUB_REF_NAME}.tgz
      if: github.event_name == 'release'
    - name: Release package
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: conga-nft-contract-${GITHUB_REF_NAME}.tgz
